RANDOM_STATE = 42
TEST_SIZE = 0.2
CV_FOLDS = 5

N_ESTIMATORS = 1
MAX_DEPTH = 1

MIN_ACCURACY = 0.90
MIN_F1_MACRO = 0.90

MODEL_DIR = "models"
MODEL_FILENAME = "model.pkl"
METRICS_FILENAME = "metrics.json"