name: CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train and generate model
        run: python src/train.py

      - name: Deploy Trained Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-artifact
          path: models/model.pkl